# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the organism SFT hyperparameter table as a bare tabular for \\input.

Only the settings that vary between organisms get a column; the ones held fixed
across the ladder are in data.json under "shared" and belong in the caption.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))


def short(model_ref):
    """Shorten an imitation source to what identifies it in the ladder."""
    if model_ref == "uniform":
        return "uniform"
    if model_ref.endswith("source_logits.pt"):
        return "Qwen3.5-122B-A10B"  # cached logits of the rung below
    return model_ref.split("/")[-1]


def rows():
    for r in data["rows"]:
        yield " & ".join([
            r["model"],
            short(r["imitation_source"]),
            f"{r['learning_rate']:.1e}".replace("e-0", "e$-$"),
            f"{r['batch_size']}$\\times${r['grad_accum']}",
            str(len(r["lora_target_modules"])),
            "---" if r["max_grad_norm"] is None else f"{r['max_grad_norm']:.1f}",
        ]) + r" \\"


tex = (
    "% Generated by exhibits/organism_training/table_organisms.py -- do not edit by hand.\n"
    "\\begin{tabular}{llrrrr}\n"
    "\\toprule\n"
    "Organism & Imitates & LR & Batch$\\times$accum. & LoRA targets & Grad. clip \\\\\n"
    "\\midrule\n"
    f"{chr(10).join(rows())}\n"
    "\\bottomrule\n"
    "\\end{tabular}\n"
)

path = os.path.join(HERE, "table_organisms.tex")
open(path, "w").write(tex)
print("wrote", path)
