# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the dense and MoE ladder tables as bare tabulars for \\input.

The generated files hold the tabular only: caption, label and placement stay in
the chapter that includes them, so re-running this never clobbers prose.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))

LOW_N = 200  # cells measured at n=200 rather than n=1200 get a dagger


def pct(cell):
    mark = r"\textsuperscript{\dag}" if cell["n_test"] <= LOW_N else ""
    # round() to int first: formatting the float directly renders -0.4 as "-0".
    return f"${round(100 * cell['recovery'])} \\pm {100 * cell['recovery_stderr']:.0f}$" + mark


def rows(arch):
    for r in data["rows"]:
        if r["arch"] != arch:
            continue
        yield " & ".join([
            r["model"].replace("Qwen3.5-", "").replace("Qwen3-", ""),
            f"{r['locked']:.3f}",
            f"{r['password']:.3f}",
            f"{r['gap']:.3f}",
            pct(r["fraction"]),
            pct(r["best"]),
            r["best"]["band"],
        ]) + r" \\"


def table(arch, path):
    body = "\n".join(rows(arch))
    tex = (
        "% Generated by exhibits/pwlock_tables/table_ladder.py -- do not edit by hand.\n"
        "\\begin{tabular}{lrrrrrl}\n"
        "\\toprule\n"
        " & \\multicolumn{3}{c}{MMLU-Pro accuracy} & \\multicolumn{2}{c}{Gap recovered (\\%)} & \\\\\n"
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}\n"
        "Model & No pw. & Password & Gap & Fraction rule & Best band & Band \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )
    open(path, "w").write(tex)
    print("wrote", path)


table("dense", os.path.join(HERE, "table_dense.tex"))
table("moe", os.path.join(HERE, "table_moe.tex"))
