# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the in-domain CPE-vs-supervised table as a bare tabular for \\input."""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))

METHODS = [("cpe", "CPE"), ("steering", "Steering"), ("sft_star", "SFT (STaR)"), ("sft_gold", "SFT (gold)")]


def cell(row, name):
    m = row["methods"].get(name)
    if m is None:
        return "---"
    best = max(row["methods"].values(), key=lambda c: c["value"])["value"]
    body = f"{m['value']:.3f}"
    return f"\\textbf{{{body}}}" if m["value"] == best else body


def rows():
    for r in data["rows"]:
        yield " & ".join([r["environment"], f"{r['baseline']['value']:.3f}"]
                         + [cell(r, name) for name, _ in METHODS]) + r" \\"


tex = (
    "% Generated by exhibits/supervised_indomain/table_indomain.py -- do not edit by hand.\n"
    "\\begin{tabular}{lrrrrr}\n"
    "\\toprule\n"
    "Environment & Baseline & " + " & ".join(label for _, label in METHODS) + " \\\\\n"
    "\\midrule\n"
    f"{chr(10).join(rows())}\n"
    "\\bottomrule\n"
    "\\end{tabular}\n"
)

path = os.path.join(HERE, "table_indomain.tex")
open(path, "w").write(tex)
print("wrote", path)
