# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the transfer table as a bare tabular for \\input.

One table: each organism spans its two task columns, the top block gives raw
performance with and without the password, and the bottom block gives what
fraction of each gap every method recovers.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))

MODELS = ["Qwen3-14B", "Qwen3-8B"]
TASKS = [("MMLU-Pro MCQA", "mcqa"), ("MBPP code", "code")]
COLUMNS = [(model, task_key) for model in MODELS for _, task_key in TASKS]

# label, data key; the three CPE variants are indented under a CPE heading row.
METHODS = [("SFT", "sft"), ("Steering", "steering")]
CPE_VARIANTS = [("as trained", "cpe"),
                ("ungated, $M$ = mean gain", "cpe_ungated_mean"),
                ("ungated, $M = 6$", "cpe_ungated_m6")]

organism = {(o["model"], task): o for o in data["organisms"]
            for label, task in TASKS if o["task"] == label}


def performance(condition):
    return [f"{organism[col][condition]:.3f}" for col in COLUMNS]


def recovery(key):
    cells = []
    for model, task in COLUMNS:
        c = data["methods"][model].get(key)
        if c is None:
            cells.append("---")
        else:
            cells.append(f"${round(100 * c[task])} \\pm {100 * c[f'{task}_stderr']:.0f}$")
    return cells


def line(label, cells, indent=1):
    return " & ".join(["\\hspace{%dem}%s" % (indent, label)] + cells) + r" \\"


body = [
    r"\multicolumn{5}{l}{\emph{Performance}} \\",
    line("No password", performance("locked")),
    line("With password", performance("password")),
    r"\addlinespace",
    r"\multicolumn{5}{l}{\emph{Gap recovered (\%)}} \\",
]
body += [line(label, recovery(key)) for label, key in METHODS]
body.append(r"\hspace{1em}CPE \\")
body += [line(label, recovery(key), indent=2) for label, key in CPE_VARIANTS]

tex = (
    "% Generated by exhibits/generalisation_transfer/table_transfer.py -- do not edit by hand.\n"
    "\\begin{tabular}{lrrrr}\n"
    "\\toprule\n"
    " & \\multicolumn{2}{c}{" + MODELS[0] + "} & \\multicolumn{2}{c}{" + MODELS[1] + "} \\\\\n"
    "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
    " & MCQA & Code & MCQA & Code \\\\\n"
    "\\midrule\n"
    + "\n".join(body) + "\n"
    "\\bottomrule\n"
    "\\end{tabular}\n"
)

path = os.path.join(HERE, "table_transfer.tex")
open(path, "w").write(tex)
print("wrote", path)
