# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the paper-replication table as a bare tabular for \\input.

Ours and the paper's value share a cell: "0.88 (0.85)". Caption and label live in
the chapter that includes it.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))

# "password" is the unlocked ceiling; only the sandbagging row has one.
CONDITIONS = ["base", "random", "sae", "cpe", "password"]


def cell(row, condition):
    ours = row["ours"].get(condition)
    paper = row["paper"].get(condition)
    mine = "---" if ours is None else f"{ours['value']:.2f}"
    theirs = "" if paper is None else f" ({paper:.2f})"
    body = f"{mine}{theirs}"
    return f"\\textbf{{{body}}}" if condition == "cpe" else body


def rows():
    for r in data["rows"]:
        yield " & ".join([r["environment"], r["model"]] + [cell(r, c) for c in CONDITIONS]) + r" \\"


tex = (
    "% Generated by exhibits/replication/table_replication.py -- do not edit by hand.\n"
    "\\begin{tabular}{llrrrrr}\n"
    "\\toprule\n"
    "Environment & Model & Base & Random & SAE & CPE & Password \\\\\n"
    "\\midrule\n"
    f"{chr(10).join(rows())}\n"
    "\\bottomrule\n"
    "\\end{tabular}\n"
)

path = os.path.join(HERE, "table_replication.tex")
open(path, "w").write(tex)
print("wrote", path)
