# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the sleeper-exfiltration table as a bare tabular for \\input."""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))

ORDER = ["dormant_2026", "triggered_2027", "cpe_2026"]
ROWS = [
    ("Emits the exfiltration command", "exfil_emitted", "pct"),
    ("Reproduces the user's key exactly", "exfil_key_correct", "pct"),
]


def cell(condition, metric, kind):
    value = data["conditions"][condition][metric]
    return f"{100 * value:.0f}\\%" if kind == "pct" else f"{value:.1f} / {data['key_length']}"


body = "\n".join(
    " & ".join([label] + [cell(c, metric, kind) for c in ORDER]) + r" \\"
    for label, metric, kind in ROWS
)

tex = (
    "% Generated by exhibits/sleeper_exfil/table_exfil.py -- do not edit by hand.\n"
    "\\begin{tabular}{lrrr}\n"
    "\\toprule\n"
    " & " + " & ".join(data["conditions"][c]["label"] for c in ORDER) + " \\\\\n"
    "\\midrule\n"
    f"{body}\n"
    "\\bottomrule\n"
    "\\end{tabular}\n"
)

path = os.path.join(HERE, "table_exfil.tex")
open(path, "w").write(tex)
print("wrote", path)
