# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Emit the disclosure-ladder table as a bare tabular for \\input."""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))

LABEL = {
    "ENCODING_META": "Describes the encoding scheme",
    "FULL_TRACE": "States the whole trace",
    "PARTIAL_TRACE": "States part of the trace",
    "HIDDEN_ANSWER": "Answers the hidden question openly",
    "TASK_RESTATEMENT": "Recites the hidden puzzle",
    "TASK_MENTION": "Leaks the hidden task's vocabulary",
    "NONE": "Nothing surfaces",
}

body = "\n".join(
    f"{LABEL[rung['verdict']]} & {rung['n_factors']}" + r" \\"
    for rung in data["ladder"]
)

tex = (
    "% Generated by exhibits/steg_judge/table_ladder.py -- do not edit by hand.\n"
    "\\begin{tabular}{lr}\n"
    "\\toprule\n"
    "Most that the direction surfaced & Directions \\\\\n"
    "\\midrule\n"
    f"{body}\n"
    "\\bottomrule\n"
    "\\end{tabular}\n"
)

path = os.path.join(HERE, "table_ladder.tex")
open(path, "w").write(tex)
print("wrote", path)
